# Generated by Django 3.0.4 on 2020-03-31 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('BrandID', models.IntegerField(db_column='BrandID', primary_key=True, serialize=False)),
                ('BrandName', models.CharField(db_column='BrandName', max_length=45)),
            ],
            options={
                'db_table': 'Brand',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('CategoryID', models.IntegerField(db_column='CategoryID', primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(db_column='CategoryName', max_length=45)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderID', models.IntegerField(db_column='OrderID', primary_key=True, serialize=False)),
                ('OrderDelivered', models.BooleanField(db_column='OrderDelivered')),
                ('OrderTimestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Order',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductID', models.IntegerField(db_column='ProductID', primary_key=True, serialize=False)),
                ('ProductName', models.CharField(blank=True, db_column='ProductName', max_length=45, null=True)),
                ('ProductQuantity', models.FloatField(blank=True, db_column='ProductQuantity', null=True)),
                ('ProductUnit', models.CharField(blank=True, db_column='ProductUnit', max_length=10, null=True)),
                ('ProductBarcode', models.CharField(blank=True, db_column='ProductBarcode', max_length=18, null=True)),
                ('ProductBrandID', models.ForeignKey(blank=True, db_column='ProductBrandID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Brand')),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='ShopType',
            fields=[
                ('ShopTypeID', models.IntegerField(db_column='ShopTypeID', primary_key=True, serialize=False)),
                ('ShopTypeName', models.CharField(db_column='ShopTypeName', max_length=45)),
            ],
            options={
                'db_table': 'ShopType',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.IntegerField(db_column='UserID', primary_key=True, serialize=False)),
                ('UserName', models.CharField(blank=True, db_column='UserName', max_length=45, null=True)),
                ('Userphonenumber', models.CharField(blank=True, db_column='UserPhoneNumber', max_length=15, null=True)),
                ('Userlatitude', models.DecimalField(blank=True, db_column='UserLatitude', decimal_places=8, max_digits=10, null=True)),
                ('Userlongitude', models.DecimalField(blank=True, db_column='UserLongitude', decimal_places=8, max_digits=11, null=True)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('Quantity', models.DecimalField(blank=True, db_column='Quantity', decimal_places=2, max_digits=4, null=True)),
                ('ShoppingItemID', models.IntegerField(db_column='ShoppingItemID', primary_key=True, serialize=False)),
                ('Notes', models.CharField(blank=True, max_length=255, null=True)),
                ('ProductID', models.ForeignKey(db_column='ProductID', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Product')),
                ('UserID', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.User')),
            ],
            options={
                'db_table': 'ShoppingItem',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('ShopID', models.IntegerField(db_column='ShopID', primary_key=True, serialize=False)),
                ('ShopName', models.CharField(db_column='ShopName', max_length=45)),
                ('Shoplatitude', models.DecimalField(db_column='ShopLatitude', decimal_places=8, max_digits=10)),
                ('Shoplongitude', models.DecimalField(db_column='ShopLongitude', decimal_places=8, max_digits=11)),
                ('ShopTypeID', models.ForeignKey(db_column='ShopTypeID', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.ShopType')),
            ],
            options={
                'db_table': 'Shop',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('ProductTypeID', models.IntegerField(db_column='ProductTypeID', primary_key=True, serialize=False)),
                ('ProductTypeName', models.CharField(db_column='ProductTypeName', max_length=45)),
                ('CategoryID', models.ForeignKey(blank=True, db_column='CategoryID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Category')),
            ],
            options={
                'db_table': 'ProductType',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='ProductTypeID',
            field=models.ForeignKey(blank=True, db_column='ProductTypeID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.ProductType'),
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('PriceID', models.IntegerField(db_column='PriceID', primary_key=True, serialize=False)),
                ('Price', models.DecimalField(blank=True, db_column='Price', decimal_places=2, max_digits=8, null=True)),
                ('ProductID', models.ForeignKey(blank=True, db_column='ProductID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Product')),
                ('ShopID', models.ForeignKey(blank=True, db_column='ShopID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Shop')),
            ],
            options={
                'db_table': 'Price',
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('OrderItemID', models.IntegerField(db_column='OrderItemID', primary_key=True, serialize=False)),
                ('Quantity', models.DecimalField(blank=True, db_column='Quantity', decimal_places=2, max_digits=4, null=True)),
                ('Notes', models.CharField(blank=True, max_length=255, null=True)),
                ('OrderID', models.ForeignKey(blank=True, db_column='OrderID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Order')),
                ('ProductID', models.ForeignKey(blank=True, db_column='ProductID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Product')),
            ],
            options={
                'db_table': 'OrderItems',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='UserID',
            field=models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.User'),
        ),
    ]
