# Generated by Django 3.0.4 on 2020-03-31 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='BrandID',
            field=models.AutoField(db_column='BrandID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='CategoryID',
            field=models.AutoField(db_column='CategoryID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='OrderID',
            field=models.AutoField(db_column='OrderID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='OrderItemID',
            field=models.AutoField(db_column='OrderItemID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='price',
            name='PriceID',
            field=models.AutoField(db_column='PriceID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProductID',
            field=models.AutoField(db_column='ProductID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='ProductTypeID',
            field=models.AutoField(db_column='ProductTypeID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shop',
            name='ShopID',
            field=models.AutoField(db_column='ShopID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shoppingitem',
            name='ShoppingItemID',
            field=models.AutoField(db_column='ShoppingItemID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shoptype',
            name='ShopTypeID',
            field=models.AutoField(db_column='ShopTypeID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='UserID',
            field=models.AutoField(db_column='UserID', primary_key=True, serialize=False),
        ),
    ]
