# Generated by Django 3.0.4 on 2020-03-31 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200331_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='Shoplatitude',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='Shoplongitude',
        ),
    ]
