# Generated by Django 3.0.4 on 2020-04-01 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20200331_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='ProductID',
        ),
        migrations.RemoveField(
            model_name='shoppingitem',
            name='ProductID',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='PriceID',
            field=models.ForeignKey(blank=True, db_column='PriceID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Price'),
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='PriceID',
            field=models.ForeignKey(db_column='PriceID', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Price'),
            preserve_default=False,
        ),
    ]
