# Generated by Django 3.0.4 on 2020-04-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20200401_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='ProductTypeName',
            field=models.CharField(db_column='ProductTypeName', max_length=45, unique=True),
        ),
    ]
