# Generated by Django 3.0.4 on 2020-04-01 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20200401_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('SearchID', models.AutoField(primary_key=True, serialize=False)),
                ('SearchTerm', models.CharField(max_length=50)),
                ('SearchTimestamp', models.DateTimeField(auto_now_add=True)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.User')),
            ],
        ),
    ]
