# Generated by Django 3.0.4 on 2020-04-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Userphonenumber',
            field=models.CharField(blank=True, db_column='UserPhoneNumber', max_length=15, unique=True),
        ),
    ]
