# Generated by Django 3.0.4 on 2020-04-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20200404_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastorder',
            name='OrderDelivered',
            field=models.BooleanField(db_column='OrderDelivered', default=False),
        ),
    ]
